server:
  port: 0

spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

greeting:
  message: Welcome to the Simple E-commerce

logging:
  level:
   com.znzn.userservice: DEBUG

# Actuator 엔드포인트 포함 내용
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans
#token:
#  expiration-time: 86400000
#  secret: user_token

