server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/znzn9292/Spring-Cloud-01.git
#          uri: file:///Users/user/Documents/znzn/study/SpringCloud/git-local-repo