server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native

  cloud:
    config:
      server:

        # 파일 시스템 Config 파일 접근
        native:
          search-locations: file://${user.home}/Documents/znzn/study/SpringCloud

        # Git 저장소 Config 파일 접근
        git:
          uri: https://github.com/znzn9292/Spring-Cloud-01.git
